import { companyData } from "@/data/company";
import type { ActivityEvent } from "@/data/activity/activityStream";
import { defaultSeo } from "@/utils/seo/staticSeo";

import {
	ORGANIZATION_ID,
	SCHEMA_CONTEXT,
	buildAbsoluteUrl,
} from "./helpers";
import type {
	DataFeedSchema,
	DataFeedItemSchema,
	PropertyValueSchema,
} from "./types";

const FEED_ID = `${defaultSeo.canonical}#live-activity-feed`;
const TIME_AGO_REGEX = /^(?<value>\d+)(?<unit>[smhd])?\s*(ago)?$/;

function timeAgoToIso(timeAgo: string): string | undefined {
	if (!timeAgo) {
		return undefined;
	}

	const match = timeAgo.trim().toLowerCase().match(TIME_AGO_REGEX);

	if (!match || !match.groups) {
		return undefined;
	}

	const value = Number.parseInt(match.groups.value, 10);

	if (Number.isNaN(value)) {
		return undefined;
	}

	const unit = match.groups.unit ?? "m";
	const now = Date.now();
	let delta = 0;

	switch (unit) {
		case "s":
			delta = value * 1000;
			break;
		case "h":
			delta = value * 60 * 60 * 1000;
			break;
		case "d":
			delta = value * 24 * 60 * 60 * 1000;
			break;
		case "m":
		default:
			delta = value * 60 * 1000;
			break;
	}

	return new Date(now - delta).toISOString();
}

function createFeedItem(
	event: ActivityEvent,
	index: number,
): DataFeedItemSchema {
	const additionalProperty: PropertyValueSchema[] = [];

	if (event.impact) {
		additionalProperty.push({
			"@type": "PropertyValue",
			name: "Impact",
			value: event.impact,
		});
	}

	if (event.tags && event.tags.length > 0) {
		additionalProperty.push({
			"@type": "PropertyValue",
			name: "Tags",
			value: event.tags.join(", "),
		});
	}

	return {
		"@type": "DataFeedItem",
		position: index + 1,
		dateCreated: timeAgoToIso(event.timeAgo),
		item: {
			"@type": "Thing",
			name: `${event.label} - ${event.actor}`.trim(),
			description: event.action,
			additionalProperty:
				additionalProperty.length > 0 ? additionalProperty : undefined,
		},
	};
}

export function buildActivityFeedSchema(
	events: ActivityEvent[],
	options: { url?: string; description?: string } = {},
): DataFeedSchema {
	const canonicalUrl = options.url
		? buildAbsoluteUrl(options.url)
		: `${defaultSeo.canonical}#live-activity-stream`;

	const feedDescription =
		options.description ??
		"Live activity notifications generated by DealScale automation.";

	return {
		"@context": SCHEMA_CONTEXT,
		"@type": "DataFeed",
		"@id": FEED_ID,
		name: "DealScale Live Activity Notifications",
		description: feedDescription,
		url: canonicalUrl,
		provider: {
			"@type": "Organization",
			name: companyData.companyName,
			"@id": ORGANIZATION_ID,
			url: defaultSeo.canonical,
		},
		dataFeedElement: events.map(createFeedItem),
	};
}
