name: 'Notify Slack'
description: 'Send a Slack message to a webhook'
inputs:
  webhook:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Status string (success|failure|info)'
    required: false
    default: info
  title:
    description: 'Title of the message'
    required: false
    default: 'Notification'
  message:
    description: 'Message body'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        STATUS: ${{ inputs.status }}
        TITLE: ${{ inputs.title }}
        MESSAGE: ${{ inputs.message }}
      run: |
        set -euo pipefail
        color="#439FE0"
        case "$STATUS" in
          success) color="#36a64f";;
          failure) color="#e01e5a";;
          *) color="#439FE0";;
        esac
        payload=$(jq -n --arg title "$TITLE" --arg msg "$MESSAGE" --arg color "$color" '
          { attachments: [ { color: $color, title: $title, text: $msg } ] }')
        curl -sS -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK"

